---
- name: Raspberry Pi Control Plane Setup
  hosts: controlplane
  become: true
  vars:
    pod_network_cidr: "10.244.0.0/16"
    service_cidr: "10.32.0.0/16"
    kubeconfig_local_path: "{{ playbook_dir }}/out/rasp_cluster_config"

  tasks:
    - name: Allow OpenSSH and other ports for Kubernetes
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 6443
        - 2379:2380
        - 10259
        - 10257
    
    - name: Pull Kubernetes images using kubeadm
      command: kubeadm config images pull

    - name: Initialize Kubernetes master node
      shell: sudo kubeadm init --pod-network-cidr "{{ pod_network_cidr }}" --service-cidr "{{ service_cidr }}"
      # no_log: true

    - name: Set up kubeconfig for admin
      shell: |
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config

    - name: Install Flannel network addon
      shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

    - name: Fetch kubeconfig file to local machine
      fetch:
        src: $HOME/.kube/config
        dest: "{{ kubeconfig_local_path }}"
        flat: yes

    - name: Get the join token for the cluster
      command: "kubeadm token list --no-headers | awk '{print $1}'"
      register: kube_join_token
      # no_log: true

    - name: Set join token variable
      set_fact:
        join_token: "{{ kube_join_token.stdout }}"
      # no_log: true

    - name: Get the CA cert hash for discovery
      command: "kubeadm token list --no-headers | awk '{print $2}'"
      register: ca_cert_hash_output
      # no_log: true

    - name: Set discovery token CA cert hash variable
      set_fact:
        discovery_token_ca_cert_hash: "{{ ca_cert_hash_output.stdout }}"
      # no_log: true