

- name: Raspberry Pi Join Cluster
  hosts: workernodes
  become: true
  vars:
    controlplane_ip: "{{ groups['controlplane'] | first }}"
    controlplane_port: "6443"

  tasks:
    - name: Check whether the worker node has joined the cluster already
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: var_check_k8s_kubelet_conf_file
      changed_when: false

    - name: Pull Kubernetes images using kubeadm
      command: kubeadm config images pull
      when: not var_check_k8s_kubelet_conf_file.stat.exists

    - name: Use the join command stored in a fact
      shell: "{{ hostvars[groups['controlplane'][0]]['join_command'] }}"
      when: not var_check_k8s_kubelet_conf_file.stat.exists


      