---
- hosts: all
  name: Validate and setup hosts
  become: true
  roles:
    - validate
    - common

- hosts: controlplane
  name: Setup controlplane
  become: true
  roles:
    - controlplane

- hosts: workernodes
  name: Setup workernodes
  become: true
  roles:
    - workernodes

- hosts: 127.0.0.1
  connection: local
  name: Setup flux on new cluster
  roles:
    - flux